using Juegardos.Website.Data;

namespace Juegardos.Website.Services;

public class GameService : IGameService
{
    private readonly List<Game> _games = new()
    {
        new() { Category = GameCategoryOptions.Action, Name = "Bubble Shot", IsFavourite = true },
        new() { Category = GameCategoryOptions.Action, Name = "Contra" },
        new() { Category = GameCategoryOptions.Action, Name = "Counter" },
        new() { Category = GameCategoryOptions.Action, Name = "Call Of Duty" },
        new() { Category = GameCategoryOptions.Action, Name = "Stardew Valley", IsFavourite = true },
        new() { Category = GameCategoryOptions.Action, Name = "Hollow Knight" },
        new() { Category = GameCategoryOptions.Action, Name = "Dark Souls" },
        new() { Category = GameCategoryOptions.Action, Name = "Outer Wilds", IsFavourite = true },
        new() { Category = GameCategoryOptions.Action, Name = "Dead Cells" },
        new() { Category = GameCategoryOptions.Action, Name = "Carto" },

        new() { Category = GameCategoryOptions.Adventure, Name = "Bubble Shot", IsFavourite = true },
        new() { Category = GameCategoryOptions.Adventure, Name = "Contra" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Counter" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Call Of Duty" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Stardew Valley", IsFavourite = true },
        new() { Category = GameCategoryOptions.Adventure, Name = "Hollow Knight" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Dark Souls" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Outer Wilds", IsFavourite = true },
        new() { Category = GameCategoryOptions.Adventure, Name = "Dead Cells" },
        new() { Category = GameCategoryOptions.Adventure, Name = "Carto" },

        new() { Category = GameCategoryOptions.Beauty, Name = "Bubble Shot", IsFavourite = true },
        new() { Category = GameCategoryOptions.Beauty, Name = "Contra" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Counter" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Call Of Duty" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Stardew Valley", IsFavourite = true },
        new() { Category = GameCategoryOptions.Beauty, Name = "Hollow Knight" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Dark Souls" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Outer Wilds", IsFavourite = true },
        new() { Category = GameCategoryOptions.Beauty, Name = "Dead Cells" },
        new() { Category = GameCategoryOptions.Beauty, Name = "Carto" },

        new() { Category = GameCategoryOptions.Races, Name = "Bubble Shot", IsFavourite = true },
        new() { Category = GameCategoryOptions.Races, Name = "Contra" },
        new() { Category = GameCategoryOptions.Races, Name = "Counter" },
        new() { Category = GameCategoryOptions.Races, Name = "Call Of Duty" },
        new() { Category = GameCategoryOptions.Races, Name = "Stardew Valley", IsFavourite = true },
        new() { Category = GameCategoryOptions.Races, Name = "Hollow Knight" },
        new() { Category = GameCategoryOptions.Races, Name = "Dark Souls" },
        new() { Category = GameCategoryOptions.Races, Name = "Outer Wilds", IsFavourite = true },
        new() { Category = GameCategoryOptions.Races, Name = "Dead Cells" },
        new() { Category = GameCategoryOptions.Races, Name = "Carto" },

        new() { Category = GameCategoryOptions.Classics, Name = "Bubble Shot", IsFavourite = true },
        new() { Category = GameCategoryOptions.Classics, Name = "Contra" },
        new() { Category = GameCategoryOptions.Classics, Name = "Counter" },
        new() { Category = GameCategoryOptions.Classics, Name = "Call Of Duty" },
        new() { Category = GameCategoryOptions.Classics, Name = "Stardew Valley", IsFavourite = true },
        new() { Category = GameCategoryOptions.Classics, Name = "Contra", Likes = 14, Dislikes = 41, Image = "https://i.blogs.es/d3fa4e/contra/450_1000.jpg", Description = "Contra es un videojuego de matamarcianos desarrollado y publicado por Konami, lanzado originalmente como un juego de arcade el 20 de febrero de 1987." },
        new() { Category = GameCategoryOptions.Classics, Name = "Super Mario", Likes = 14, Dislikes = 41, Image = "https://pressover.news/wp-content/uploads/2021/09/71RuXB-P8lL._AC_SL1333_-1068x801.jpg", Description = "Super Mario es una serie de videojuegos de plataformas creados por la empresa desarrolladora Nintendo y protagonizados por su mascota, Mario." },
        new() { Category = GameCategoryOptions.Classics, Name = "Sonic The Hedgedog", Likes = 14, Dislikes = 41, Image = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_3ds_download_software_7/SI_3DSDS_3DSonicTheHedgehog_image1600w.jpg", Description = "Sonic the Hedgehog es un videojuego desarrollado por Sonic Team y distribuido por Sega en 1991 para la videoconsola Sega Mega Drive protagonizado por Sonic y donde también hizo su debut. Este videojuego de plataformas fue, durante mucho tiempo, considerado el buque insignia de Sega, el ejemplo a seguir para sus futuros juegos. Incluso llegó a dar nombre a uno de sus equipos de desarrollo: Sonic Team.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Classics, Name = "Aladdin", Likes = 14, Dislikes = 41, Image = "https://m.media-amazon.com/images/I/81JplUUuSyL._AC_SL1500_.jpg", Description = "Disney's Aladdin es un videojuego de plataformas basado en la película de 1992 del mismo nombre desarrollada por Virgin Games USA. El juego fue lanzado por Sega para Sega Genesis el 11 de noviembre de 1993 como uno de varios juegos basados en la película, incluido otro juego que fue lanzado en el mismo mes por Capcom para Super NES." },
        new() { Category = GameCategoryOptions.Classics, Name = "Bomberman", Likes = 14, Dislikes = 41, Image = "https://tn.com.ar/resizer/dxoMkqUJQ5O9UGgUHNyW051dJFE=/767x0/smart/filters:quality(60)/cloudfront-us-east-1.images.arcpublishing.com/artear/IGXEDYC6FTVTTCEVC7EIA4KO74.jpg", Description = "Bomberman es una franquicia de videojuegos estratégico-laberínticos originalmente desarrollada por Hudson Soft y actualmente por Konami. El juego original fue desarrollado por Shinichi Nakamoto y fue lanzado en 1983 para PC y posteriormente para Famicom.​ Desde entonces se han lanzado nuevos juegos." },

        new() { Category = GameCategoryOptions.Click, Name = "Monkey Island 2", Likes = 14, Dislikes = 41, Image = "https://cdn.cloudflare.steamstatic.com/steam/apps/32460/header.jpg?t=1571778532", Description = "Monkey Island 2: LeChuck's Revenge es una aventura gráfica realizada por LucasArts y publicada en diciembre de 1991,1 aunque la versión española lo hizo en abril de 1992,​ que fue realizada con el mismo motor que The Secret of Monkey Island, y fue distribuida originalmente en disquetes, con gráficos VGA para luego ser distribuida por separado y más tarde junto con la primera parte, en CD-ROM. El juego tiene un inesperado final, del que se ha dicho que es el más desconcertante de la historia de los videojuegos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Broken Sword", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-broken-sword.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Broken Sword es una serie de aventuras gráficas creada por el diseñador de videojuegos Charles Cecil de Revolution Software. Gira en torno a las aventuras de George Stobbart y Nicole Collard y sus búsquedas a lo largo de varios países partiendo de la historia y la mitología. Los dos primeros juegos se basaban en la clásica interfaz de point and click, que son gráficos realizados a mano, mientras que las dos últimas entregas fueron en formato 3D." },
        new() { Category = GameCategoryOptions.Click, Name = "Grim Fandango", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-grim-fandango.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Grim Fandango es probablemente el clásico de apuntar y hacer clic más conocido de los años 90, y por una buena razón. Las aventuras de Manny a través de la tierra de los muertos están fuertemente inspiradas por una serie de influencias del mundo real, y son estas influencias las que hacen que la experiencia se sienta verdaderamente genuina. Bueno... tan genuina como puede ser una historia sobre personas esqueléticas, de todos modos." },
        new() { Category = GameCategoryOptions.Click, Name = "Beneath A Steel Sky", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-beneath-a-steel-sky.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Como muchos de los títulos de esta era, Beneath a Steel Sky está comenzando a mostrar su edad en el departamento gráfico. Sin embargo, eso no quita nada a su fantástica historia y maravillosa actuación de voz, ni hace que los momentos de comedia bufonesca que se encuentran a lo largo del juego sean menos divertidos. En todo caso, solo sirve para enfatizar su brillantez." },
        new() { Category = GameCategoryOptions.Click, Name = "Myst", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-myst.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "A los hermanos Rand y Robyn Miller les tomó solo dos años convertir su idea de un juego de aventuras para adultos en una realidad, lo cual fue una hazaña impresionante considerando la escala y la ambición del proyecto. Tampoco se tomaron medidas a medias, y el resultado final resultó ser un éxito tanto para los jugadores como para los críticos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Day of the Tentacle", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-dott.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Tim Schafer a menudo es reconocido como el responsable de popularizar el crowdfunding de videojuegos , pero se podría argumentar que también es el responsable de la reciente reactivación de los juegos de aventura de apuntar y hacer clic. Ha trabajado en algunos de los mejores títulos que el género tiene para ofrecer, pero su primer papel protagónico llegó en Day of the Tentacle de 1993 ." },
        new() { Category = GameCategoryOptions.Click, Name = "Sam & Max Hit The Road", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-sam-and-max.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Sam & Max Hit the Road fue uno de los primeros videojuegos en presentar protagonistas con voz completa, y el equipo de LucasArts no escatimó en gastos a la hora de contratar talentos. La decisión de apostar por actores de voz profesionales realmente valió la pena, ya que muchos críticos señalaron que la actuación de voz es una de las mayores fortalezas del juego." },
        new() { Category = GameCategoryOptions.Click, Name = "Full Throttle", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-full-throttle.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "La historia y la jugabilidad de Full Throttle son excelentes, pero es el protagonista principal del juego lo que realmente lo hace destacar. Ben Throttle es la definición misma de rudo, y el difunto gran Roy Conrad hizo un trabajo fantástico al darle vida al personaje. Está increíblemente bien escrito y sus técnicas creativas de resolución de problemas seguramente traerán una sonrisa a los rostros de los jugadores.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Loom", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-loom.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "A primera vista, puede que no sea obvio que Loom es un juego de LucasArts debido a las drásticas diferencias en el tono y la jugabilidad en comparación con sus otros títulos. En muchos sentidos, se siente más como un creador que experimenta con una variedad de ideas en conflicto que como un intento genuino de hacer un videojuego." },
        new() { Category = GameCategoryOptions.Click, Name = "Indiana Jones And The Fate Of Atlantis", Likes = 14, Dislikes = 41, Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-ijatfoa.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "LucasArts, al ser una subsidiaria de LucasFilm, le dio al equipo acceso a algunas de las mejores licencias de películas de todos los tiempos. Además, a diferencia de muchos de los otros títulos con licencia que se hacían en esa época, los juegos de LucasArts basados ​​en películas eran realmente buenos. muy bueno Indiana Jones and the Fate of Atlantis es el ejemplo perfecto de la forma correcta de adaptar una franquicia cinematográfica a un videojuego." },

        new() { Category = GameCategoryOptions.Sports, Name = "Rocket League", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/hnoJTWPk34kRZtcMCsrph5-970-80.jpg.webp", Description = "Algunas ideas son tan bellamente simples que es imposible imaginar un mundo sin ellas. Rocket League es uno de esos ejemplos. Irrumpiendo en la escena (y, memorablemente, gratis con PS Plus) en 2015, Rocket League ve equipos de hasta cuatro parachoques bloqueados en lo que es esencialmente 'fútbol con autos'.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "Lonely Mountains Downhill", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/WsChgpnALbnvjnk4b5igEU-970-80.jpg.webp", Description = "El mejor juego de deportes al que nunca has jugado. Rectifica eso lo antes posible. Yuxtaponiendo muertes espantosas con un paisaje impresionante, corres a toda velocidad a un motorista cubo-hombre a través de cuatro montañas de recorridos desafiantes y duraderos. " },
        new() { Category = GameCategoryOptions.Sports, Name = "Tony Hawk’s Pro Skater 1", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/bGRnemjgLoNtYGnAEg5jNc-970-80.jpg.webp", Description = "La nostalgia tiene la mala costumbre de jugarte malas pasadas. Enciende la serie original de Tony Hawk en PlayStation y es probable que tus recuerdos teñidos de rosa de beber Red Bull y escuchar Goldfinger en un bucle se desvanezcan. Es fangoso, complicado y carece de la fluidez de los esfuerzos futuros de THPS." },
        new() { Category = GameCategoryOptions.Sports, Name = "Art of Rally", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/dTYf4hGB3vnDDYB49TGEEn-970-80.jpg.webp", Description = "Es una pena que Art of Rally no haya recibido la atención que merecía cuando se lanzó en septiembre de 2020, porque es uno de los juegos de carreras más estilísticos y hermosos hasta la fecha. Este es un juego independiente que se centra en la era dorada de los rallies, con muchos autos clásicos, incluido un número de la infame categoría del Grupo B." },
        new() { Category = GameCategoryOptions.Sports, Name = "Out Of The Park Baseball 22", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/TBRFCa38kMLgGp3si6wvsB-970-80.jpg.webp", Description = "Fuera de los Estados Unidos, Football Manager ha sido considerado durante mucho tiempo el único juego en la ciudad en lo que respecta a los juegos de estrategia deportiva, pero hay un montón de simulador de banquillo acurrucado en ese punto ciego colectivo. OOTP es tan profundo como su contraparte de pelota de fútbol, ​​absorbiendo horas mientras negocia intercambios, promueve y degrada cargos entre clubes afiliados y se deleita en robar bases y aplastar jonrones.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "F1 2020", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/T9RRdBBJERteoE3cu9hbrZ-970-80.png.webp", Description = "La franquicia oficial de Fórmula Uno ha pasado por un momento tumultuoso en la última década, y los fanáticos de la serie recordarán la decepción de F1 2014. Afortunadamente, ahora está de nuevo en plena forma y F1 2020 es uno de los mejores juegos de carreras que puedes comprar. Este Dia. Ofrece una experiencia de carreras muy diferente a un juego como Forza Horizon 4, pero si te gustan los autos de ultra alta velocidad con ese sonido de motor espeluznante que se precipita por los 22 circuitos únicos, la experiencia F1 2020 no tiene rival." },
        new() { Category = GameCategoryOptions.Sports, Name = "Fight Night Champion", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/iECpY3LyjSX6fMHAzTo9wk-970-80.jpg.webp", Description = "Disponible en Xbox Series X gracias al programa de compatibilidad con versiones anteriores de Microsoft, Fight Night Champion es la recreación perfecta de la dulce ciencia. En un rincón, EA combina su excelente tratamiento habitual de los deportes alternativos con controles de precisión y gráficos que aún, hoy en día, pueden detenerlo en seco. En el otro, el Modo Campeón de Fight Night Champion. Anunciando una ola de narrativas completas que puntuaron los juegos deportivos durante la próxima década, la historia de Andre Bishop nunca ha sido mejor." },
        new() { Category = GameCategoryOptions.Sports, Name = "FIFA 22", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/9ZRh2qX75kUwbucuun4GBg-970-80.jpg.webp", Description = "Pagar para ganar, guión, roto. FIFA no sería FIFA sin los jugadores haciendo cola para dispararle, y la mecánica de la caja de botín de apertura de paquetes en Ultimate Team sin duda necesita transparencia adicional. Sin embargo, considerado como un paquete, hay pocos juegos de deportes, o incluso juegos de cualquier género, que le den tanto a cambio de su dinero. ", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "Super Mega Baseball 3", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/TSGirX2CpZPAjW5VyLFatZ-970-80.jpg.webp", Description = "¿Béisbol? Sí. ¿Mega? Uh-uh. ¿Súper? Definitivamente. Cabezudos y jugadores ficticios hacen de este tercer esfuerzo de Metalhead Software una verdadera experiencia de regreso al futuro, que brinda mecánicas retro a un mundo HD. " },
        new() { Category = GameCategoryOptions.Sports, Name = "Football Manager 2022", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/ZoJPWKEuLEpBrf42wbBkrd-970-80.jpg.webp", Description = "Tanto si creciste jugando Championship Manager como si acabas de adoptar la franquicia Football Manager, sabrás lo adictiva y precisa que es la simulación, que refleja el fútbol de la vida real. Todo, desde la negociación de transferencias y la oferta de nuevos contratos hasta la capacitación diaria y la interacción con la prensa, depende de usted, o no, si prefiere que el personal se encargue de todo. Si bien FM no te permite controlar directamente a los jugadores en el campo, es una simulación táctica mucho más completa que cualquier otra cosa en el mercado." },

        new() { Category = GameCategoryOptions.Puzzle, Name = "Professor Layton and the Miracle Mask", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/adcb6ffe08a9a273b9f9d84dd95ae27b-970-80.jpg.webp", Description = "Esta serie de larga duración tiene muchos misterios, pero lo más destacado es esta historia del encantador profesor y su intento de comprender la verdad detrás del Caballero Enmascarado y los llamados milagros que está usando para dejar perplejos a los residentes de Monte d' O.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Lara Croft Go", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/iH5MAyCVQHPyQpADv2UA5A-970-80.png.webp", Description = "Estamos acostumbrados a ver a Lara en modo de acción, pero este encantador rompecabezas se centra en la investigación que también exige su trabajo de arqueología. El modo de juego sigue la fórmula establecida por los otros juegos de Go de Square Enix Montreal. Lara se enfrentará a todo, desde serpientes hasta arañas y púas en su camino para resolver el misterio de la Reina del Veneno. " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Room", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/nSNRYB2CXd4SDjRyQi6moE-970-80.jpg.webp", Description = "Este juego explora el significado de la vida y su relación con un quinto elemento extraño y espectral llamado Nulo. Como puede suponer, las cosas se ponen bastante raras bastante rápido. Pero también se vuelven muy divertidos. El estilo de arte gótico del juego crea inmediatamente el estado de ánimo para un descenso críptico a la locura, desbloqueando los secretos de muchos objetos intrincadamente detallados para descubrir lo que el antiguo habitante de la habitación sabía sobre Null." },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Swapper", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/5KdmejKnsujwree5WWam8S-970-80.png.webp", Description = "No hay muchos juegos de rompecabezas que te hagan pensar seriamente en la vida, la conciencia y el significado del yo. Pero The Swapper despierta con éxito esas cavilaciones con sinceridad. Juegas como un astronauta que busca una gran estación de investigación abandonada, tratando de encontrar respuestas a dónde han ido los investigadores mientras encuentran un escape seguro. Recoges orbes para desbloquear nuevas áreas, lo que significa usar un dispositivo extraño para hacer copias de ti mismo para navegar por el diseño extraño de la estación.  " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Talos Principle", Likes = 14, Dislikes = 41, Image = "https://origin.mos.cms.futurecdn.net/zJjKUwAMYh82ANrqHj5nVG-970-80.jpg.webp", Description = "Otro excelente ejemplo de cómo combinar narrativa y rompecabezas, The Talos Principle es uno de los juegos más cerebrales que existen. Es el juego de una persona pensante, uno para los jugadores que quieren tener su juego con una gran cantidad de filosofía. ", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Fez", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/TwTBZ6SXZQFzfUDeEf2AU9-970-80.jpg.webp", Description = "Ver no es solo creer en este rompecabezas alucinante. Ver es la realidad. Fez literalmente presenta una nueva perspectiva en los juegos de rompecabezas. Gira el mundo cúbico para recolectar los fragmentos del hexaedro dorado, que ha roto y hecho añicos las mismas reglas del tiempo y el espacio. (¡Mira, tu maestro te dijo que habría un uso para la geometría en el mundo real!) " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Picross 3D Round 2", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/6sFdg6HczmjsoYJ6yeENYW-970-80.jpg.webp", Description = "La escultura y la carpintería tienen que ver con la paciencia. Cincelar tu medio, rasurar un pequeño fragmento a la vez, exige una mano firme y un ojo agudo. También necesitarás esa mano y ese ojo para dominar Picross 3D Ronda 2. Cada rompecabezas consiste en crear una linda talla en madera de un objeto objetivo. Para hacer el producto final, tendrás que hacer algo de magia matemática para decidir dónde y cómo se talla cada bloque. Round 2 aumenta la complejidad de las posibles creaciones gracias a la introducción de superficies curvas, lo que significa que se necesita una geometría mental más deliciosa para llegar a la solución correcta." },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Witness", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/rSXTkPzY4Hhg7zhTYMPy8j-970-80.jpg.webp", Description = "Dibuja una línea. Eso es técnicamente lo único que necesitas hacer en The Witness. Pero en manos de Jonathan Blow, esa simple misiva se estira, se retuerce y se vuelve a imaginar en uno de los juegos de rompecabezas más alucinantes que se hayan creado.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Portal", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/hxcT4h64ofjzyggDCw4G7f-970-80.jpg.webp", Description = "Ya se ha derramado mucha tinta sobre estos dos clásicos de Valve. Ambos se han presentado como ejemplos de juegos como arte, escritura hilarante e innovación en el diseño. Ambos son tan buenos que sería imposible elegir solo uno para incluirlo en esta lista. La premisa de los juegos de usar portales para atravesar habitaciones cada vez más elaboradas exige una lógica espacial desgarradora en sus niveles finales. La historia puntiaguda sobre el poder y el capitalismo ayuda a elevar un concepto ya excelente al reino de la perfección. El canto de GLaDOS es la guinda del pastel. " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Tetris", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/vJAokqiRnNniuL3MSorJEM-970-80.jpg.webp", Description = "Sí, uno de los videojuegos más antiguos sigue siendo uno de los mejores. Las formas de tetromino ahora son elementos icónicos de la cultura pop. El concepto ha inspirado a muchos otros diseñadores de juegos. Tetris todavía se lleva la corona de los juegos de rompecabezas." },

        new() { Category = GameCategoryOptions.Shots, Name = "Destiny 2", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/V8mXUpw6yWB6Ypv997fxPf-970-80.jpg.webp", Description = "Bungie siempre ha diseñado los mejores tiradores del mundo a lo largo de sus 30 años de historia, y Destiny 2 es un ejemplo casi perfecto de por qué el estudio sigue siendo la CABRA. Este juego de disparos en línea continúa creciendo y evolucionando con su base de jugadores, y ofrece una mecánica de combate bien diseñada que te recordará a los mejores juegos de Halo .y un mundo compartido reactivo que es bastante diferente a todo lo demás. Ya sea que corras solo o con un grupo de guardianes, completes desafíos semanales por diversión o reúnas el equipo y la experiencia necesarios para enfrentar las incursiones más desafiantes, Destiny 2 es una joya de juego de disparos. Nunca ha habido un mejor momento para saltar y probarlo; Destiny 2: The Witch Queen ya está disponible, una nueva expansión que es perfecta para jugadores nuevos, antiguos y veteranos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Shots, Name = "Ratchet & Clank: Rift Apart", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/PeqreZbWXioTouVxXkcQ8-970-80.jpg.webp", Description = "Insomniac Games no recibe suficiente crédito por su fantástico diseño de armas. Ratchet & Clank Rift Apart es una exclusiva de PS5 verdaderamente fenomenal, un escaparate del sistema como ningún otro, que demuestra la velocidad del SSD, la necesidad de un televisor 4K en esta nueva generación y lo inmersivo que puede ser realmente el controlador DualSense. Sin embargo, Rift Apart también es un increíble juego de disparos en tercera persona para todas las edades. Es divertido de jugar, genuinamente divertido y presenta un amplio arsenal de armas ingeniosas que se ven, se sienten y se manejan de manera diferente entre sí. Si está buscando un descanso de Battle Royales y shooters militares, no podríamos recomendar esta excelente experiencia para un solo jugador. Pruébalo y estamos bastante seguros de que te enamorarás de Rift Apart. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Fortnite", Likes = 14, Dislikes = 41, Image = "https://www.esportmaniacos.com/wp-content/uploads/2022/03/Fortnite-scaled1.jpg", Description = "Fortnite se ha convertido en un auténtico fenómeno cultural. Tanto es así que puede ser demasiado fácil descartar lo divertido que es como un juego de disparos en tercera persona. Epic Games ha estado simplificando silenciosamente los sistemas de combate subyacentes y refinando la mecánica de disparo durante años, reduciendo el grupo de armas y mejorando la movilidad de los jugadores para ayudar a crear una experiencia más rápida e inmediata. Si una vez te rechazaron debido al edificio, tal vez deberías darle otra oportunidad ahora: los jugadores todavía están creando estructuras absurdas a gran velocidad, pero tienes más herramientas para navegar alrededor de ellas y alcanzar tu objetivo. Divertido, colorido y en constante expansión, Fortnite es realmente uno de los mejores juegos de disparos de la era moderna. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Halo Infinite", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/Ad8UeGJczS4MK6TVxjHbA9-970-80.jpg.webp", Description = "343 Industries tiene el peso del mundo sobre sus hombros con Halo Infinite. La serie ha tenido problemas para encontrar su lugar en la última década, y Halo Infinite tuvo que sentar bases sólidas para la futura expansión a medida que Xbox Game Studios busca una nueva generación. Y lo que recibimos fue bastante asombroso. La campaña lleva a Master Chief a una aventura de mundo abierto para conquistar y explorar una instalación de Halo, cumpliendo el sueño ofrecido por primera vez por Combat Evolved hace 20 años. El modo multijugador es igualmente emocionante, una oferta gratuita para PC, Xbox One y Xbox Series X que vuelve a las raíces de los juegos de arena de Halo 2 y Halo 3. Es un paquete fantástico." },
        new() { Category = GameCategoryOptions.Shots, Name = "Call of Duty Warzone", Likes = 14, Dislikes = 41, Image = "https://elchapuzasinformatico.com/wp-content/uploads/2020/03/Call-of-Duty-Warzone.jpg", Description = "Call of Duty: Warzone transporta a los jugadores al corazón de la volátil batalla geopolítica de la Guerra Fría, a principios de la década de 1980.", IsOutstanding = true },
        new() { Category = GameCategoryOptions.Shots, Name = "Deathloop", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/ALuGtnW5zFTU2udLMHJ4gB-970-80.jpg.webp", Description = "Deathloop es un muy buen momento. Es colorido y enérgico, elegante y cuidadosamente diseñado, lo que lo empuja a completar un ciclo perfecto de asesinatos en un solo día. Arkane tomó la experiencia que obtuvo al trabajar en Dishonored, Prey y Wolfenstein y la convirtió en un juego de disparos en primera persona verdaderamente dinámico, el tipo de experiencia que te mantendrá adivinando durante su larga duración. Los disparos se sienten fantásticos, es muy divertido luchar contra la IA y la variedad de poderes sobrenaturales que se ponen en tus manos solo ayudan a amplificar la carnicería. Deathloop es un juego obligatorio para todos los fanáticos de los juegos de disparos. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Titanfall 2", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/BtPSE5uKSwqcoLES6LHtAY-970-80.jpeg.webp", Description = "Titanfall 2 es un juego de disparos en primera persona subestimado de la última década. Es posible que Respawn Entertainment esté ocupado con Apex Legends ahora, pero si aún no lo ha jugado, se está perdiendo una de las mejores campañas en años. Es una historia sobre un piloto y su compañero robot mecánico, mientras exploran un mundo alienígena en constante disputa debido a las facciones enemigas. Corres por las paredes y te deslizas por el suelo, disparando a todo lo que ves con una serie de ingeniosas armas. Pero cada vez que te subes a tu robot, todo cambia, y ambas experiencias se vuelven una, ya que se entrelazan perfectamente entre sí. La historia ofrece niveles que siempre traen algo nuevo a la mesa, expandiendo las posibilidades de cada elemento del juego a niveles impensables." },
        new() { Category = GameCategoryOptions.Shots, Name = "Gears 5", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/Pq2YaFwVNSjNTJNJYJXphF-970-80.jpg.webp", Description = "No sería una lista de los mejores tiradores sin al menos un juego de Gears. Gears 5, aunque tal vez no sea la primera opción para los veteranos de la serie, aún captura lo que hizo que la franquicia fuera tan interesante a lo largo de los años. Una versión aún más refinada de disparar a cubierto, combinada con nuevas armas y un grupo completamente nuevo de enemigos para luchar mientras la protagonista Kait Diaz descubre el Swarm en una nueva y emocionante historia. Pero puedes saltar directamente incluso si no has jugado ninguna de las entradas anteriores, especialmente si estás interesado en jugar en modo cooperativo con tus amigos. La adición de Escape, un modo para tres jugadores en el que el trabajo en equipo es obligatorio mientras te infiltras en una colmena enemiga, colocas explosivos y tienes que huir de la escena de inmediato, es una adición bienvenida a un panorama multijugador ya variado. Y en Gears 5, ciertamente hay algo para todos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Shots, Name = "PUBG: Battlegrounds", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/XzFy5CXpR5edqJX3EDto4i-970-80.jpg.webp", Description = "El Battle Royale original es mejor que nunca. Si bien PlayerUnkown's Battlegrounds ha cedido algo de terreno a Apex Legends, Call of Duty: Warzones y Fortnites de este mundo, todavía tiene una ventaja táctica sobre su competencia más inmediata. Es más lento e implacable para los principiantes, con un mayor enfoque en la supervivencia, lo que solo ayuda a elevar los momentos de victoria incremental. Este juego de disparos en tercera persona recientemente se convirtió en un juego gratuito, imbuyendo a sus servidores con una nueva oportunidad de vida; hay una gran cantidad de contenido disponible en PUBG, desde una amplia gama de mapas hasta armas personalizables, y realmente deberías darle otra oportunidad si buscas un descanso de los otros Battle Royales principales. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Half-Life Alyx", Likes = 14, Dislikes = 41, Image = "https://cdn.mos.cms.futurecdn.net/sxSWinExz2y6HB76Rgijqh-970-80.jpg.webp", Description = "Muchos señalarán a Half-Life 2 como uno de los mejores juegos de disparos de todos los tiempos y, si bien sigue siendo una experiencia fantástica y formativa, hay verdadera magia en Half-Life Alyx. Esta exclusiva de realidad virtual muestra el poder y el potencial de la realidad virtual para los tiradores, brindándole un nivel de control y libertad sin precedentes para experimentar en un mundo al que estábamos tan desesperados por regresar. Al darnos un control complejo sobre las armas en nuestras manos y al diseñar escenarios verdaderamente reactivos, Valve pudo ofrecer uno de los mejores juegos de disparos de todos los tiempos. Confía en nosotros cuando te decimos que nunca has jugado nada tan inmersivo como Half-Life Alyx , un juego imprescindible si puedes conseguir la tecnología necesaria para ejecutarlo. " },
    };

    public async Task<List<GameCategory>> GetCategoriesWithGames()
    {
        await Task.Delay(1000);
        var gameCategories = new List<GameCategory>();
        gameCategories.Add(new() { Name = "Acción", Games = _games.Where(x => x.Category == GameCategoryOptions.Action).ToList() });
        gameCategories.Add(new() { Name = "Aventura", Games = _games.Where(x => x.Category == GameCategoryOptions.Adventure).ToList() });
        gameCategories.Add(new() { Name = "Belleza", Games = _games.Where(x => x.Category == GameCategoryOptions.Beauty).ToList() });
        gameCategories.Add(new() { Name = "Carrera", Games = _games.Where(x => x.Category == GameCategoryOptions.Races).ToList() });
        gameCategories.Add(new() { Name = "Clásicos", Games = _games.Where(x => x.Category == GameCategoryOptions.Classics).ToList() });
        gameCategories.Add(new() { Name = "Click", Games = _games.Where(x => x.Category == GameCategoryOptions.Click).ToList() });
        gameCategories.Add(new() { Name = "Deportes", Games = _games.Where(x => x.Category == GameCategoryOptions.Sports).ToList() });
        gameCategories.Add(new() { Name = "Puzzle", Games = _games.Where(x => x.Category == GameCategoryOptions.Puzzle).ToList() });
        gameCategories.Add(new() { Name = "Tiros", Games = _games.Where(x => x.Category == GameCategoryOptions.Shots).ToList() });
        return gameCategories;
    }

    public async Task<Game?> GetGame(string name)
    {
        await Task.Delay(1000);
        foreach (var game in _games)
            if (game.Name.ToLower().Contains(name.ToLower()))
                return game;
        return null;
    }

    public async Task<Game?> GetOutstandingGame()
    {
        await Task.Delay(1000);
        foreach (var game in _games)
            if (game.IsOutstanding)
                return game;
        return null;
    }

    public async Task<List<Game>> SearchGames(string nameOrCategory, GameFilters? filters = null)
    {
        await Task.Delay(1000);
        var games = new List<Game>();
        foreach (var game in _games)
            if (game.Name.ToLower().Contains(nameOrCategory.ToLower()) || game.Category.ToLower().Contains(nameOrCategory.ToLower()))
                games.Add(game);

        if (filters is null)
            return games;

        if (!string.IsNullOrWhiteSpace(filters.Category))
            games = games.Where(x => x.Category == filters.Category).ToList();

        if (!string.IsNullOrWhiteSpace(filters.Popularity))
        {
            if (filters.Popularity == GamePopularityOptions.MorePopulars)
                games = games.OrderByDescending(x => x.Likes).ToList();
            else if (filters.Popularity == GamePopularityOptions.LessPopulars)
                games = games.OrderByDescending(x => x.Dislikes).ToList();
        }

        if (!string.IsNullOrWhiteSpace(filters.Order))
        {
            if (filters.Order == GameOrderOptions.Ascendant)
                games = games.OrderBy(x => x.Name).ToList();
            else if (filters.Order == GameOrderOptions.Descendant)
                games = games.OrderByDescending(x => x.Name).ToList();
        }
            
        return games;
    }
}
