using Juegardos.Website.Data;
using System.Globalization;

namespace Juegardos.Website.Services;

public class GameService : IGameService
{
    private readonly List<Game> _games = new()
    {
        new() { Category = GameCategoryOptions.Action, Name = "Subway Clash 2", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/69357/webp_subway-clash-200x120.webp?1638519599", Description = "Tu próxima misión está a punto de comenzar en Subway Clash 2. Coge tu equipo, revisa tu armamento y dirígete a la batalla en este emocionante juego en línea. En este juego de acción, tú y tu equipo tendréis que asaltar un antiguo depósito de metro en Moscú que sirve de escondite actual a los Testigos de Illyich. Se trata de una secta de fanáticos religiosos liderada por el infame terrorista Bonch-Buyevich, cuyo objetivo es detonar una serie de bombas sucias en túneles del metro de toda la ciudad.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Archers.io", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/69447/webp_Archers-io-200x120.webp?1639488403", Description = "Una guerra está a punto de comenzar en Archers.io. ¿Vencerás a tus oponentes o te harán morder el polvo en este emocionante juego .io? Desafía a otros jugadores de todo el mundo en este juego de peleas mientras tomas el control de un solo arquero. ¡Necesitará hacer amigos y rápido! Reúne a tantos arqueros como puedas antes de intentar acabar con los clanes de los otros jugadores.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Angry Sharks", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25230/jpeg_200X120_177873_1623330185.jpg?1630790870", Description = "Son grandes, malos, ¡y tienen muy malas pulgas! ¡Prepárate para unirte a ellos en Angry Sharks! ¡Los peces gordos de este juego de tiburones son de armas tomar! Acompáñalos mientras se comen todo lo que se les pone a tiro e intentan crecer aun más. ¡Tendrás que ayudarlos a evitar peces globo, formaciones de coral afiladas y mucho bidones de material tóxico!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Miami Crime Simulator 3D", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24226/jpeg_200X120_175074_1553002332.jpg?1630789565", Description = "Las calles de esta archiconocida metrópolis están a rebosar de delincuentes. Ayuda a poner fin a la oleada de crímenes en Miami Crime Simulator 3D. Solo tú puedes cazar y eliminar a todos los criminales que se dedican a aterrorizar a los ciudadanos. ¡Y tienes que conseguirlo sin ayuda de nadie! Defiéndete con pistolas, granadas y otras armas alucinantes en esta locura de juego de acción.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Boxing Random", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25249/webp_200X120_177892_1624970487.webp?1630790892", Description = "¡Prepárate para pelear en Boxing Random! ¿Te convertirás en el próximo rey o reina del ring en este loco juego de deportes? Lucharás contra tus oponentes en todas partes, desde gimnasios hasta cimas de montañas nevadas. ¡Tampoco usarás solo tus puños! ¡Hay al menos algunas armas que aparecerán mientras juegas este juego de acción retro!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Combat Strike 2", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/22837/webp_200X120_170449_1502203702.webp?1630787765", Description = "Únete al equipo y ponte manos a la obra en este juego de disparos en primera persona. Tendrás que perseguir y eliminar a tus rivales en una serie de arenas mortales. En cada misión podrás usar una gran variedad de armas alucinantes para superar los desafíos en templos antiguos, ubicaciones exóticas, ¡y hasta edificios de oficinas y un casino en Las Vegas!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Stree Rage Fighter", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23831/webp_200X120_173556_1540545884.webp?1630789035", Description = "¡La única forma de dominar estas calles es con tus propios puños! Ah, y con tus pies... y tal vez con algunos cuchillos. Busca todo tipo de armas mientras luchas por recuperar la ciudad de una despiadada pandilla de forajidos en este juego de acción retro.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Squid Game 2", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/69379/webp_squid-game-2-200x120.webp?1638792139", Description = "Prepárate para más desafíos mortales en Squid Game 2. ¿Llegarás a la ronda final de este juego en línea basado en la popular serie de Netflix? Estás totalmente en la ruina, así que parece que tendrás que convertirte en un jugador de la próxima edición de El juego del calamar. Hay mucho dinero en efectivo que ganar, pero tendrás que llegar hasta el final de varias versiones increíblemente peligrosas de juegos infantiles populares.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Bullet Party", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24651/webp_200X120_176700_1567519486.webp?1630790123", Description = "¡De más está decir que esta fiesta será muy alocada y un poco peligrosa! ¿Cuánto tiempo lograrás sobrevivir cuando te enfrentes a jugadores de todo el mundo en este juego de disparos en primera persona? Participa en varias peleas para eliminarlos a todos. Hay ciertos objetivos que debes alcanzar en cada batalla repleta de acción.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Action, Name = "Short Life", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24115/webp_200X120_174643_1550669207.webp?1630789419", Description = "Este tipo valiente está intentando abrirse camino a través de una serie de peligrosas pistas de obstáculos en este intenso juego de acción. Cada vez se vuelven más peligrosas así que necesita de tu ayuda. Únete a él mientras salta por encima de cuchillas, esquiva barriles explosivos e intenta evitar pisar cualquier pincho superafilado!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },

        new() { Category = GameCategoryOptions.Adventure, Name = "Uphill Rush 8", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/61098/webp_200X120_178179_1634906266.webp?1635516245", Description = "Es una nueva y emocionante entrega de la serie de juegos Uphill Rush. Elige un flotador y deslízate por los toboganes más locos del parque acuático. En este juego de aventuras, puedes recorrer los toboganes más extravagantes con unos flotadores todavía más estrambóticos. Trata de guardar el equilibrio, pues caerte de uno de estos toboganes tan imponentes podría ser fatal.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Impostor", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25083/webp_200X120_177703_1611403044.webp?1630790684", Description = "Alguien está haciendo fechorías en el corazón de este laboratorio. En Impostor, ¡ese alguien eres tú! Tu objetivo es sembrar el caos por todas partes en este juego de supervivencia multijugador inspirado en el popular juego para dispositivos móviles Among Us. Ataca a tus compañeros de trabajo, escabúllete a través de conductos de ventilación y sabotea distintos equipos. ", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Adam and Eve: GO 3", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25265/webp_200X120_177908_1624369182.webp?1630790911", Description = "Únete al habilidoso hombre de las cavernas en otra increíble aventura en Adam and Eve: GO 3. En esta entrega de la divertida y desafiante serie de Adam and Eve, Adam va en busca de montones de fruta deliciosa. ¡Tendrás que ayudarle a idear soluciones inteligentes mientras se ocupa de exploradores hambrientos, serpientes peligrosas y otros hombres de las cavernas inmersos en sus propias aventuras!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Blob Giant 3D", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25293/webp_200X120_177942_1624970580.webp?1630790944", Description = "Este tipo gelatinoso está decidido a seguir creciendo en Blob Giant 3D. ¿Puedes ayudarlo a alcanzar sus metas en este juego de correr de gigantes? Está decidido a convertirse en una masa lo más grande posible en este juego de plataformas 3D. ¡Acompáñalo mientras absorbe masas más pequeñas y corre hacia la línea de meta al final de cada nivel!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Rex en Río", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24128/webp_200X120_174704_1550668897.webp?1630789436", Description = "¡Este tiranosaurio está listo para viajar Río! Pero no le interesa ir a la playa, ¡sino que prefiere pasar sus vacaciones devorando trabajadores para probar la comida local! Únete a este diabólico dinosaurio mientras destruye la famosa ciudad costera en este salvaje juego de acción.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Construcción", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23826/webp_200X120_173524_1540473820.webp?1630789029", Description = "En este juego en línea, puedes construir, diseñar y personalizar un mundo entero. Dale rienda suelta a tu imaginación mientras pruebas todas las herramientas, paisajes y otras funciones.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Amazing Spider Police", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24202/webp_200X120_174982_1553698277.webp?1630789534", Description = "Este valiente policía combate enemigos en ambos lados de la ley en este alocado y delirante juego de acción. ¿Puedes ayudarlo a capturar criminales y policías mientras recorre la ciudad y se roba algún que otro auto?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "World Crafts", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23796/webp_200X120_173420_1539938785.webp?1630788988", Description = "Ingresa a un mundo 3D repleto de maravillas en este juego en línea. ¡Puedes construirlo, personalizarlo y hacerlo tuyo! ¡Deja volar tu imaginación!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Subway Surf", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23662/webp_200X120_172886_1536003916.webp?1630788815", Description = "¡Un oficial de tránsito está persiguiendo de cerca a este patinador! Por suerte, ¡el chico cuenta con una tabla voladora futurista! ¿Puedes ayudarlo a evitar que el policía lo envíe a prisión en este loco juego de skate en línea?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Adventure, Name = "Fuerzas especiales", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24272/webp_200X120_175223_1554475025.webp?1630789624", Description = "Puedes atacar sin piedad a tus enemigos o defender tu territorio en este juego de disparos en primera persona. Sube a las colinas y prepárate para la batalla de tu vida mientras intentas derrotar a tus enemigos con una ametralladora.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },

        new() { Category = GameCategoryOptions.Beauty, Name = "Extreme Makeover", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/39340/webp_200X120_178066_1630404890.webp?1634219592", Description = "Hay una chica con estilo a la que le vendría muy bien tu ayuda en Extreme Makeover. Es hora de crear un nuevo e increíble look para ella en este genial juego en línea." },
        new() { Category = GameCategoryOptions.Beauty, Name = "Year Round Fashionista: Curly", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/61408/webp_200X120_178060_1630399468.webp?1637764582", Description = "¡Prepárate para 12 meses de estilismo en Year Round Fashionista: Curly! ¿Cuántos conjuntos increíbles puedes crear en este juego de diseño en línea? ¡Esta amante de la moda quiere encontrar ropa que vaya bien con su fabuloso pelo rizado! ¿Puedes ayudarla a crear un look impresionante para cada mes del año en este juego de moda?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Boda de ensueño", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24185/webp_200X120_174929_1551966712.webp?1630789511", Description = "¡Ya es hora de que comience el casamiento de esta novia y está llegando muy tarde! Lo que es peor, perdió su vestido y accesorios. ¿Puedes ayudarla e encontrarlos rápidamente y a prepararse para el gran día en este juego de vestidos y objectos ocultos?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Peinados de unicornio", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24456/webp_200X120_175931_1560946806.webp?1630789868", Description = "A esta chica le fascinan los unicornios y estuvo pensando hacerse un nuevo peinado. ¡Quiere uno que no sea nada convencional! ¿Podrías ayudarla a hacerse un peinado que sea totalmente mágico en este juego de cambio de imagen?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Arte de pintura de uñas", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24013/webp_200X120_174271_1547025289.webp?1630789284", Description = "Puedes crear cientos de estilos increíbles en el salón de manicura en este juego de maquillaje en línea. Dale rienda suelta a tu imaginación mientras experimentas diferentes tipos y colores de pinturas para uñas. Pero primero, deberás darle a tus clientes una rápida manicura.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Diseñadora de zapatos", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24042/webp_200X120_174370_1547556711.webp?1630789322", Description = "Esta atareada diseñadora tiene todo tipo de proyectos en los que trabajar. Necesita tu ayuda en este juego de diseño en línea. Ingresa a su estudio donde está a punto de comenzar a crear su próxima colección increíble de zapatos. ¡Puedes darle algunos consejos mientras diseña desde clásicos zapatos de tacones a zapatos completamente alocados!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Moda de celebridades", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24268/webp_200X120_175204_1554722248.webp?1630789619", Description = "Ya es hora de que estas cinco celebridades asistan a un excluvio evento de moda. Quieres verse espléndidas en este juego de vestidos. ¿puedes ayudar a cada una con su peinado, maquillaje y vestido?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Supermuñeca: transformación", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24581/webp_200X120_176419_1565782009.webp?1630790030", Description = "Esta famosa superheroína quiere probar un fabuloso cambio de imagen. ¿Podrás crear un nuevo estilo tan extraño como fantástico en este increíble juego de cambio de imagen? ¡Pero primero necesita deshacerse de unos molestos granitos!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Pintura facial", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24425/webp_200X120_175827_1560418535.webp?1630789828", Description = "Es hora de que esta chica a la moda cree un nuevo estilo en este juego de maquillaje. Probará algunos productos geniales para pintarse la cara de forma alocada. También quiere probarse muchas prendas a la moda.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Beauty, Name = "Princesas: concurso de moda", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/22644/webp_200X120_169997_1498053263.webp?1630787519", Description = "¿Cuál de todas estas famosas princesas ganará el concurso? Averigua quién merece ser la amante de la moda más grandiosa en este juego de vestir para chicas.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },

        new() { Category = GameCategoryOptions.Races, Name = "Evo-F2 Racing", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24330/webp_200X120_175458_1557318850.webp?1630789701", Description = "En este increíble juego de carreras 3D, puedes probar diferentes vehículos. ¡Usa un genial auto deportivo o prueba acelerar al máximo una vieja camioneta o hasta una pala mecánica!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Rally Point 4", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/57037/webp_200X120_178157_1634137649.webp?1634799687", Description = "¡Alcanza la máxima velocidad en Rally Point 4! ¿Cómo de rápido llegarás a la meta en este emocionante juego en línea? Tendrás que moverte rápido para vencer al reloj en este juego de carreras. Supera los puntos de control mientras intentas llegar a la meta en cada zona al volante de coches, camiones y demás. ¡Irás a toda velocidad por carreteras que te llevarán a través de desiertos y selvas, así como a lo largo de los bordes de los acantilados de una montaña cubierta de nieve!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Speed Boat Extreme Racing", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/69291/webp_200X120_178224_1637596600.webp?1638186079", Description = "Alcanza la máxima velocidad y despega de las rampas en Speed Boat Extreme Racing. ¿Será tu embarcación la primera en cruzar la línea de meta en este emocionante juego en línea? Toma el control de una de las diferentes lanchas superrápidas al comenzar cada intensa competición. Puedes enfrentarte a un amigo o al ordenador en este juego de carreras en 3D.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Highway Bike Simulator", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24675/webp_200X120_176798_1569327787.webp?1630790155", Description = "Podrás correr a toda velocidad por geniales autopistas y superar a cualquier vehículo que intente retrasarte en este juego de conducir en 3D. Súbete a una motocicleta y prepárate para recorrer fantásticos desiertos, bosques y valles nevados. Puedes probar cuatro motocicletas distintas, y hay muchos modos de juego tan diferentes como desafiantes que pondrás a prueba tus habilidades.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Camiones monstruos extremos", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24601/webp_200X120_176485_1565781519.webp?1630790056", Description = "En este juego de carreras en 3D te esperan cinco fabulosos camiones monstruos distintos. Siéntate al volante para conducir a toda velocidad por un desierto y luego un bosque lleno de rampas, colinas y otros obstáculos tan extremos como alocados. Hay decenas de pistas en ambas áreas que pondrán a prueba tus habilidades de conducir un vehículo virtual.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "City Bus Simulator", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23928/webp_200X120_173903_1543485950.webp?1630789173", Description = "¡Manejar un autobús es mucho más difícil de lo que parece! ¿Pero puedes hacerte cargo, cierto? Inténtalo en este juego de simulación. ¿Puedes conducir este vehículo por todas estas rutas con curvas sin chocar nada?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Moto X3M: Bike Racing", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23684/webp_200X120_172979_1534764969.webp?1630788841", Description = "La emoción nunca falta en Moto X3M. ¡Prepárate para correr por tu vida atravesando aros, sobrevolando chuchillas giratorias gigantes y mucho más! Toma el control de uno de estos temerarios pilotos, salta en moto y supera decenas de desafiantes y peligrosas pistas de obstáculos. Correrás por playas y cuevas mientras te enfrentas a peligros muy locos.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Agame Stunt Cars", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23793/webp_200X120_173404_1556006840.webp?1630788984", Description = "Las posibilidades son infinitas en este asombroso juego de carrera. Personaliza tu auto antes de recorrer las pistas y hacerlo volar por los aires.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "MX Off-Road Mountain Bike", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/25136/webp_200X120_177760_1615556371.webp?1630790752", Description = "Prepárate para la carrera de tu vida en MX Off-Road Mountain Bike. Es hora de poner los pies en polvorosa. Bueno, ¡en este caso las ruedas! ¿Llegarás al final de todas estas increíbles pistas forestales de este juego de bicis tan realista? Tendrás que evitar piedras y otros peligros a la vez que impides que tu ciclista se caiga por una colina, se choque contra una roca o acabe en una situación mucho peor que precise la asistencia del equipo de rescate de montaña.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Races, Name = "Crazy Stunt Cars 2", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/23514/webp_200X120_172295_1527498770.webp?1630788627", Description = "En este alocado juego de conducir, puedes personalizar algunos autos potentes, vehículos militares y más. Cámbiales la pintura y mejora su manejo antes de salir volando por las rampas y averigua si puedes lograr algunos épicos giros de 360°.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },

        new() { Category = GameCategoryOptions.Classics, Name = "Contra", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://i.blogs.es/d3fa4e/contra/450_1000.jpg", Description = "Contra es un videojuego de matamarcianos desarrollado y publicado por Konami, lanzado originalmente como un juego de arcade el 20 de febrero de 1987." },
        new() { Category = GameCategoryOptions.Classics, Name = "Super Mario", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://pressover.news/wp-content/uploads/2021/09/71RuXB-P8lL._AC_SL1333_-1068x801.jpg", Description = "Super Mario es una serie de videojuegos de plataformas creados por la empresa desarrolladora Nintendo y protagonizados por su mascota, Mario." },
        new() { Category = GameCategoryOptions.Classics, Name = "Sonic The Hedgedog", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_3ds_download_software_7/SI_3DSDS_3DSonicTheHedgehog_image1600w.jpg", Description = "Sonic the Hedgehog es un videojuego desarrollado por Sonic Team y distribuido por Sega en 1991 para la videoconsola Sega Mega Drive protagonizado por Sonic y donde también hizo su debut. Este videojuego de plataformas fue, durante mucho tiempo, considerado el buque insignia de Sega, el ejemplo a seguir para sus futuros juegos. Incluso llegó a dar nombre a uno de sus equipos de desarrollo: Sonic Team.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Classics, Name = "Aladdin", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://m.media-amazon.com/images/I/81JplUUuSyL._AC_SL1500_.jpg", Description = "Disney's Aladdin es un videojuego de plataformas basado en la película de 1992 del mismo nombre desarrollada por Virgin Games USA. El juego fue lanzado por Sega para Sega Genesis el 11 de noviembre de 1993 como uno de varios juegos basados en la película, incluido otro juego que fue lanzado en el mismo mes por Capcom para Super NES." },
        new() { Category = GameCategoryOptions.Classics, Name = "Bomberman", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://tn.com.ar/resizer/dxoMkqUJQ5O9UGgUHNyW051dJFE=/767x0/smart/filters:quality(60)/cloudfront-us-east-1.images.arcpublishing.com/artear/IGXEDYC6FTVTTCEVC7EIA4KO74.jpg", Description = "Bomberman es una franquicia de videojuegos estratégico-laberínticos originalmente desarrollada por Hudson Soft y actualmente por Konami. El juego original fue desarrollado por Shinichi Nakamoto y fue lanzado en 1983 para PC y posteriormente para Famicom.​ Desde entonces se han lanzado nuevos juegos." },
        new() { Category = GameCategoryOptions.Classics, Name = "Mahjong EZ", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24353/webp_200X120_175581_1557746795.webp?1630789731", Description = "Esta es una versión del clásico juego de mesa que es ideal para jugadores principiantes y expertos por igual. ¿Qué tan rápido lograrás unir todas las fichas? Incluso puedes deshacer movimientos si piensas en una mejor jugada.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Classics, Name = "Ludo de 4 jugadores", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24550/webp_200X120_176291_1564410375.webp?1630789991", Description = "En esta versión del ludo, se puede jugar de hasta cuatro jugadores. Desafía a tus amigos y familiares en el clásico juego de mesa. ¿Lograrás llevar tus cuatro fichas hasta el triángulo de llegada antes que los demás?", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Classics, Name = "Tic Tac Toe Paper", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24701/webp_200X120_176940_1570013609.webp?1630790187", Description = "En esta versión en línea del clásico juego puedes desafiar a la computadora o a un amigo. ¿Jugarás con las X o las O? ¡Intenta vencer a tu rival en un desafío al mejor de 3, 5 o 10!", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Classics, Name = "Leyenda de las damas", Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24338/webp_200X120_175511_1556787324.webp?1630789711", Description = "¿Lograrás convertirte en una leyenda en esta versión en línea del clásico juego de mesa? Enfréntate a diferentes oponentes virtuales mientras dominas los modos fácil, medio y difíciles.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },
        new() { Category = GameCategoryOptions.Classics, Name = "Leyenda del solitario", IsFavourite = true, Image = "https://gamesgamescdn.com/system/static/thumbs/spil_thumb_big/24242/webp_200X120_175119_1553697527.webp?1630789585", Description = "¿Lograrás convertirte en una leyenda en esta versión en línea del clásico juego? No pierdas de vista el reloj mientras reúnen las cartas lo más rápido que puedas.", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500) },

        new() { Category = GameCategoryOptions.Click, Name = "Monkey Island 2", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.cloudflare.steamstatic.com/steam/apps/32460/header.jpg?t=1571778532", Description = "Monkey Island 2: LeChuck's Revenge es una aventura gráfica realizada por LucasArts y publicada en diciembre de 1991,1 aunque la versión española lo hizo en abril de 1992,​ que fue realizada con el mismo motor que The Secret of Monkey Island, y fue distribuida originalmente en disquetes, con gráficos VGA para luego ser distribuida por separado y más tarde junto con la primera parte, en CD-ROM. El juego tiene un inesperado final, del que se ha dicho que es el más desconcertante de la historia de los videojuegos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Broken Sword", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-broken-sword.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Broken Sword es una serie de aventuras gráficas creada por el diseñador de videojuegos Charles Cecil de Revolution Software. Gira en torno a las aventuras de George Stobbart y Nicole Collard y sus búsquedas a lo largo de varios países partiendo de la historia y la mitología. Los dos primeros juegos se basaban en la clásica interfaz de point and click, que son gráficos realizados a mano, mientras que las dos últimas entregas fueron en formato 3D." },
        new() { Category = GameCategoryOptions.Click, Name = "Grim Fandango", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-grim-fandango.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Grim Fandango es probablemente el clásico de apuntar y hacer clic más conocido de los años 90, y por una buena razón. Las aventuras de Manny a través de la tierra de los muertos están fuertemente inspiradas por una serie de influencias del mundo real, y son estas influencias las que hacen que la experiencia se sienta verdaderamente genuina. Bueno... tan genuina como puede ser una historia sobre personas esqueléticas, de todos modos." },
        new() { Category = GameCategoryOptions.Click, Name = "Beneath A Steel Sky", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-beneath-a-steel-sky.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Como muchos de los títulos de esta era, Beneath a Steel Sky está comenzando a mostrar su edad en el departamento gráfico. Sin embargo, eso no quita nada a su fantástica historia y maravillosa actuación de voz, ni hace que los momentos de comedia bufonesca que se encuentran a lo largo del juego sean menos divertidos. En todo caso, solo sirve para enfatizar su brillantez." },
        new() { Category = GameCategoryOptions.Click, Name = "Myst", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-myst.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "A los hermanos Rand y Robyn Miller les tomó solo dos años convertir su idea de un juego de aventuras para adultos en una realidad, lo cual fue una hazaña impresionante considerando la escala y la ambición del proyecto. Tampoco se tomaron medidas a medias, y el resultado final resultó ser un éxito tanto para los jugadores como para los críticos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Day of the Tentacle", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-dott.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Tim Schafer a menudo es reconocido como el responsable de popularizar el crowdfunding de videojuegos , pero se podría argumentar que también es el responsable de la reciente reactivación de los juegos de aventura de apuntar y hacer clic. Ha trabajado en algunos de los mejores títulos que el género tiene para ofrecer, pero su primer papel protagónico llegó en Day of the Tentacle de 1993 ." },
        new() { Category = GameCategoryOptions.Click, Name = "Sam & Max Hit The Road", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-sam-and-max.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "Sam & Max Hit the Road fue uno de los primeros videojuegos en presentar protagonistas con voz completa, y el equipo de LucasArts no escatimó en gastos a la hora de contratar talentos. La decisión de apostar por actores de voz profesionales realmente valió la pena, ya que muchos críticos señalaron que la actuación de voz es una de las mayores fortalezas del juego." },
        new() { Category = GameCategoryOptions.Click, Name = "Full Throttle", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-full-throttle.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "La historia y la jugabilidad de Full Throttle son excelentes, pero es el protagonista principal del juego lo que realmente lo hace destacar. Ben Throttle es la definición misma de rudo, y el difunto gran Roy Conrad hizo un trabajo fantástico al darle vida al personaje. Está increíblemente bien escrito y sus técnicas creativas de resolución de problemas seguramente traerán una sonrisa a los rostros de los jugadores.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Click, Name = "Loom", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-loom.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "A primera vista, puede que no sea obvio que Loom es un juego de LucasArts debido a las drásticas diferencias en el tono y la jugabilidad en comparación con sus otros títulos. En muchos sentidos, se siente más como un creador que experimenta con una variedad de ideas en conflicto que como un intento genuino de hacer un videojuego." },
        new() { Category = GameCategoryOptions.Click, Name = "Indiana Jones And The Fate Of Atlantis", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2020/10/pnc-ijatfoa.jpg?q=50&fit=crop&w=740&dpr=1.5", Description = "LucasArts, al ser una subsidiaria de LucasFilm, le dio al equipo acceso a algunas de las mejores licencias de películas de todos los tiempos. Además, a diferencia de muchos de los otros títulos con licencia que se hacían en esa época, los juegos de LucasArts basados ​​en películas eran realmente buenos. muy bueno Indiana Jones and the Fate of Atlantis es el ejemplo perfecto de la forma correcta de adaptar una franquicia cinematográfica a un videojuego." },

        new() { Category = GameCategoryOptions.Sports, Name = "Rocket League", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/hnoJTWPk34kRZtcMCsrph5-970-80.jpg.webp", Description = "Algunas ideas son tan bellamente simples que es imposible imaginar un mundo sin ellas. Rocket League es uno de esos ejemplos. Irrumpiendo en la escena (y, memorablemente, gratis con PS Plus) en 2015, Rocket League ve equipos de hasta cuatro parachoques bloqueados en lo que es esencialmente 'fútbol con autos'.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "Lonely Mountains Downhill", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/WsChgpnALbnvjnk4b5igEU-970-80.jpg.webp", Description = "El mejor juego de deportes al que nunca has jugado. Rectifica eso lo antes posible. Yuxtaponiendo muertes espantosas con un paisaje impresionante, corres a toda velocidad a un motorista cubo-hombre a través de cuatro montañas de recorridos desafiantes y duraderos. " },
        new() { Category = GameCategoryOptions.Sports, Name = "Tony Hawk’s Pro Skater 1", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/bGRnemjgLoNtYGnAEg5jNc-970-80.jpg.webp", Description = "La nostalgia tiene la mala costumbre de jugarte malas pasadas. Enciende la serie original de Tony Hawk en PlayStation y es probable que tus recuerdos teñidos de rosa de beber Red Bull y escuchar Goldfinger en un bucle se desvanezcan. Es fangoso, complicado y carece de la fluidez de los esfuerzos futuros de THPS." },
        new() { Category = GameCategoryOptions.Sports, Name = "Art of Rally", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/dTYf4hGB3vnDDYB49TGEEn-970-80.jpg.webp", Description = "Es una pena que Art of Rally no haya recibido la atención que merecía cuando se lanzó en septiembre de 2020, porque es uno de los juegos de carreras más estilísticos y hermosos hasta la fecha. Este es un juego independiente que se centra en la era dorada de los rallies, con muchos autos clásicos, incluido un número de la infame categoría del Grupo B." },
        new() { Category = GameCategoryOptions.Sports, Name = "Out Of The Park Baseball 22", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/TBRFCa38kMLgGp3si6wvsB-970-80.jpg.webp", Description = "Fuera de los Estados Unidos, Football Manager ha sido considerado durante mucho tiempo el único juego en la ciudad en lo que respecta a los juegos de estrategia deportiva, pero hay un montón de simulador de banquillo acurrucado en ese punto ciego colectivo. OOTP es tan profundo como su contraparte de pelota de fútbol, ​​absorbiendo horas mientras negocia intercambios, promueve y degrada cargos entre clubes afiliados y se deleita en robar bases y aplastar jonrones.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "F1 2020", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/T9RRdBBJERteoE3cu9hbrZ-970-80.png.webp", Description = "La franquicia oficial de Fórmula Uno ha pasado por un momento tumultuoso en la última década, y los fanáticos de la serie recordarán la decepción de F1 2014. Afortunadamente, ahora está de nuevo en plena forma y F1 2020 es uno de los mejores juegos de carreras que puedes comprar. Este Dia. Ofrece una experiencia de carreras muy diferente a un juego como Forza Horizon 4, pero si te gustan los autos de ultra alta velocidad con ese sonido de motor espeluznante que se precipita por los 22 circuitos únicos, la experiencia F1 2020 no tiene rival." },
        new() { Category = GameCategoryOptions.Sports, Name = "Fight Night Champion", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/iECpY3LyjSX6fMHAzTo9wk-970-80.jpg.webp", Description = "Disponible en Xbox Series X gracias al programa de compatibilidad con versiones anteriores de Microsoft, Fight Night Champion es la recreación perfecta de la dulce ciencia. En un rincón, EA combina su excelente tratamiento habitual de los deportes alternativos con controles de precisión y gráficos que aún, hoy en día, pueden detenerlo en seco. En el otro, el Modo Campeón de Fight Night Champion. Anunciando una ola de narrativas completas que puntuaron los juegos deportivos durante la próxima década, la historia de Andre Bishop nunca ha sido mejor." },
        new() { Category = GameCategoryOptions.Sports, Name = "FIFA 22", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/9ZRh2qX75kUwbucuun4GBg-970-80.jpg.webp", Description = "Pagar para ganar, guión, roto. FIFA no sería FIFA sin los jugadores haciendo cola para dispararle, y la mecánica de la caja de botín de apertura de paquetes en Ultimate Team sin duda necesita transparencia adicional. Sin embargo, considerado como un paquete, hay pocos juegos de deportes, o incluso juegos de cualquier género, que le den tanto a cambio de su dinero. ", IsFavourite = true },
        new() { Category = GameCategoryOptions.Sports, Name = "Super Mega Baseball 3", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/TSGirX2CpZPAjW5VyLFatZ-970-80.jpg.webp", Description = "¿Béisbol? Sí. ¿Mega? Uh-uh. ¿Súper? Definitivamente. Cabezudos y jugadores ficticios hacen de este tercer esfuerzo de Metalhead Software una verdadera experiencia de regreso al futuro, que brinda mecánicas retro a un mundo HD. " },
        new() { Category = GameCategoryOptions.Sports, Name = "Football Manager 2022", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/ZoJPWKEuLEpBrf42wbBkrd-970-80.jpg.webp", Description = "Tanto si creciste jugando Championship Manager como si acabas de adoptar la franquicia Football Manager, sabrás lo adictiva y precisa que es la simulación, que refleja el fútbol de la vida real. Todo, desde la negociación de transferencias y la oferta de nuevos contratos hasta la capacitación diaria y la interacción con la prensa, depende de usted, o no, si prefiere que el personal se encargue de todo. Si bien FM no te permite controlar directamente a los jugadores en el campo, es una simulación táctica mucho más completa que cualquier otra cosa en el mercado." },

        new() { Category = GameCategoryOptions.Puzzle, Name = "4 en linea", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://my-live-01.slatic.net/p/5e1fa4498061348dfde1f5ccea5ad649.jpg", Description = "Conecta 4 (también conocido como 4 en Linea en algunas versiones) es un juego de mesa para dos jugadores distribuido por Hasbro, en el que se introducen fichas en un tablero vertical con el objetivo de alinear cuatro consecutivas de un mismo color.", IsFavourite = true, IsOutstanding = true, HowToPlay = "El objetivo del 4 en línea es alinear cuatro fichas sobre un tablero formado por seis filas y siete columnas. Cada jugador dispone de 21 fichas de un color (por lo general, rojas o amarillas). Por turnos, los jugadores deben introducir una ficha en la columna que prefieran (siempre que no esté completa) y ésta caerá a la posición más baja. Gana la partida el primero que consiga alinear cuatro fichas consecutivas de un mismo color en horizontal, vertical o diagonal.​ Si todas las columnas están llenas pero nadie ha hecho una fila válida, hay empate.", Controls = new() { "Click izquierdo - Seleccionar ficha", "Arrastrar mouse - Mover ficha", "Soltar click izquierdo - Colocar ficha" } },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Professor Layton and the Miracle Mask", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/adcb6ffe08a9a273b9f9d84dd95ae27b-970-80.jpg.webp", Description = "Esta serie de larga duración tiene muchos misterios, pero lo más destacado es esta historia del encantador profesor y su intento de comprender la verdad detrás del Caballero Enmascarado y los llamados milagros que está usando para dejar perplejos a los residentes de Monte d' O.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Lara Croft Go", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/iH5MAyCVQHPyQpADv2UA5A-970-80.png.webp", Description = "Estamos acostumbrados a ver a Lara en modo de acción, pero este encantador rompecabezas se centra en la investigación que también exige su trabajo de arqueología. El modo de juego sigue la fórmula establecida por los otros juegos de Go de Square Enix Montreal. Lara se enfrentará a todo, desde serpientes hasta arañas y púas en su camino para resolver el misterio de la Reina del Veneno. " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Room", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/nSNRYB2CXd4SDjRyQi6moE-970-80.jpg.webp", Description = "Este juego explora el significado de la vida y su relación con un quinto elemento extraño y espectral llamado Nulo. Como puede suponer, las cosas se ponen bastante raras bastante rápido. Pero también se vuelven muy divertidos. El estilo de arte gótico del juego crea inmediatamente el estado de ánimo para un descenso críptico a la locura, desbloqueando los secretos de muchos objetos intrincadamente detallados para descubrir lo que el antiguo habitante de la habitación sabía sobre Null." },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Swapper", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/5KdmejKnsujwree5WWam8S-970-80.png.webp", Description = "No hay muchos juegos de rompecabezas que te hagan pensar seriamente en la vida, la conciencia y el significado del yo. Pero The Swapper despierta con éxito esas cavilaciones con sinceridad. Juegas como un astronauta que busca una gran estación de investigación abandonada, tratando de encontrar respuestas a dónde han ido los investigadores mientras encuentran un escape seguro. Recoges orbes para desbloquear nuevas áreas, lo que significa usar un dispositivo extraño para hacer copias de ti mismo para navegar por el diseño extraño de la estación.  " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Talos Principle", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://origin.mos.cms.futurecdn.net/zJjKUwAMYh82ANrqHj5nVG-970-80.jpg.webp", Description = "Otro excelente ejemplo de cómo combinar narrativa y rompecabezas, The Talos Principle es uno de los juegos más cerebrales que existen. Es el juego de una persona pensante, uno para los jugadores que quieren tener su juego con una gran cantidad de filosofía. ", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Fez", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/TwTBZ6SXZQFzfUDeEf2AU9-970-80.jpg.webp", Description = "Ver no es solo creer en este rompecabezas alucinante. Ver es la realidad. Fez literalmente presenta una nueva perspectiva en los juegos de rompecabezas. Gira el mundo cúbico para recolectar los fragmentos del hexaedro dorado, que ha roto y hecho añicos las mismas reglas del tiempo y el espacio. (¡Mira, tu maestro te dijo que habría un uso para la geometría en el mundo real!) " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Picross 3D Round 2", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/6sFdg6HczmjsoYJ6yeENYW-970-80.jpg.webp", Description = "La escultura y la carpintería tienen que ver con la paciencia. Cincelar tu medio, rasurar un pequeño fragmento a la vez, exige una mano firme y un ojo agudo. También necesitarás esa mano y ese ojo para dominar Picross 3D Ronda 2. Cada rompecabezas consiste en crear una linda talla en madera de un objeto objetivo. Para hacer el producto final, tendrás que hacer algo de magia matemática para decidir dónde y cómo se talla cada bloque. Round 2 aumenta la complejidad de las posibles creaciones gracias a la introducción de superficies curvas, lo que significa que se necesita una geometría mental más deliciosa para llegar a la solución correcta." },
        new() { Category = GameCategoryOptions.Puzzle, Name = "The Witness", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/rSXTkPzY4Hhg7zhTYMPy8j-970-80.jpg.webp", Description = "Dibuja una línea. Eso es técnicamente lo único que necesitas hacer en The Witness. Pero en manos de Jonathan Blow, esa simple misiva se estira, se retuerce y se vuelve a imaginar en uno de los juegos de rompecabezas más alucinantes que se hayan creado.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Portal", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/hxcT4h64ofjzyggDCw4G7f-970-80.jpg.webp", Description = "Ya se ha derramado mucha tinta sobre estos dos clásicos de Valve. Ambos se han presentado como ejemplos de juegos como arte, escritura hilarante e innovación en el diseño. Ambos son tan buenos que sería imposible elegir solo uno para incluirlo en esta lista. La premisa de los juegos de usar portales para atravesar habitaciones cada vez más elaboradas exige una lógica espacial desgarradora en sus niveles finales. La historia puntiaguda sobre el poder y el capitalismo ayuda a elevar un concepto ya excelente al reino de la perfección. El canto de GLaDOS es la guinda del pastel. " },
        new() { Category = GameCategoryOptions.Puzzle, Name = "Tetris", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/vJAokqiRnNniuL3MSorJEM-970-80.jpg.webp", Description = "Sí, uno de los videojuegos más antiguos sigue siendo uno de los mejores. Las formas de tetromino ahora son elementos icónicos de la cultura pop. El concepto ha inspirado a muchos otros diseñadores de juegos. Tetris todavía se lleva la corona de los juegos de rompecabezas." },

        new() { Category = GameCategoryOptions.Shots, Name = "Destiny 2", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/V8mXUpw6yWB6Ypv997fxPf-970-80.jpg.webp", Description = "Bungie siempre ha diseñado los mejores tiradores del mundo a lo largo de sus 30 años de historia, y Destiny 2 es un ejemplo casi perfecto de por qué el estudio sigue siendo la CABRA. Este juego de disparos en línea continúa creciendo y evolucionando con su base de jugadores, y ofrece una mecánica de combate bien diseñada que te recordará a los mejores juegos de Halo .y un mundo compartido reactivo que es bastante diferente a todo lo demás. Ya sea que corras solo o con un grupo de guardianes, completes desafíos semanales por diversión o reúnas el equipo y la experiencia necesarios para enfrentar las incursiones más desafiantes, Destiny 2 es una joya de juego de disparos. Nunca ha habido un mejor momento para saltar y probarlo; Destiny 2: The Witch Queen ya está disponible, una nueva expansión que es perfecta para jugadores nuevos, antiguos y veteranos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Shots, Name = "Ratchet & Clank: Rift Apart", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/PeqreZbWXioTouVxXkcQ8-970-80.jpg.webp", Description = "Insomniac Games no recibe suficiente crédito por su fantástico diseño de armas. Ratchet & Clank Rift Apart es una exclusiva de PS5 verdaderamente fenomenal, un escaparate del sistema como ningún otro, que demuestra la velocidad del SSD, la necesidad de un televisor 4K en esta nueva generación y lo inmersivo que puede ser realmente el controlador DualSense. Sin embargo, Rift Apart también es un increíble juego de disparos en tercera persona para todas las edades. Es divertido de jugar, genuinamente divertido y presenta un amplio arsenal de armas ingeniosas que se ven, se sienten y se manejan de manera diferente entre sí. Si está buscando un descanso de Battle Royales y shooters militares, no podríamos recomendar esta excelente experiencia para un solo jugador. Pruébalo y estamos bastante seguros de que te enamorarás de Rift Apart. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Fortnite", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://www.esportmaniacos.com/wp-content/uploads/2022/03/Fortnite-scaled1.jpg", Description = "Fortnite se ha convertido en un auténtico fenómeno cultural. Tanto es así que puede ser demasiado fácil descartar lo divertido que es como un juego de disparos en tercera persona. Epic Games ha estado simplificando silenciosamente los sistemas de combate subyacentes y refinando la mecánica de disparo durante años, reduciendo el grupo de armas y mejorando la movilidad de los jugadores para ayudar a crear una experiencia más rápida e inmediata. Si una vez te rechazaron debido al edificio, tal vez deberías darle otra oportunidad ahora: los jugadores todavía están creando estructuras absurdas a gran velocidad, pero tienes más herramientas para navegar alrededor de ellas y alcanzar tu objetivo. Divertido, colorido y en constante expansión, Fortnite es realmente uno de los mejores juegos de disparos de la era moderna. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Halo Infinite", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/Ad8UeGJczS4MK6TVxjHbA9-970-80.jpg.webp", Description = "343 Industries tiene el peso del mundo sobre sus hombros con Halo Infinite. La serie ha tenido problemas para encontrar su lugar en la última década, y Halo Infinite tuvo que sentar bases sólidas para la futura expansión a medida que Xbox Game Studios busca una nueva generación. Y lo que recibimos fue bastante asombroso. La campaña lleva a Master Chief a una aventura de mundo abierto para conquistar y explorar una instalación de Halo, cumpliendo el sueño ofrecido por primera vez por Combat Evolved hace 20 años. El modo multijugador es igualmente emocionante, una oferta gratuita para PC, Xbox One y Xbox Series X que vuelve a las raíces de los juegos de arena de Halo 2 y Halo 3. Es un paquete fantástico." },
        new() { Category = GameCategoryOptions.Shots, Name = "Call of Duty Warzone", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://elchapuzasinformatico.com/wp-content/uploads/2020/03/Call-of-Duty-Warzone.jpg", Description = "Call of Duty: Warzone transporta a los jugadores al corazón de la volátil batalla geopolítica de la Guerra Fría, a principios de la década de 1980." },
        new() { Category = GameCategoryOptions.Shots, Name = "Deathloop", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/ALuGtnW5zFTU2udLMHJ4gB-970-80.jpg.webp", Description = "Deathloop es un muy buen momento. Es colorido y enérgico, elegante y cuidadosamente diseñado, lo que lo empuja a completar un ciclo perfecto de asesinatos en un solo día. Arkane tomó la experiencia que obtuvo al trabajar en Dishonored, Prey y Wolfenstein y la convirtió en un juego de disparos en primera persona verdaderamente dinámico, el tipo de experiencia que te mantendrá adivinando durante su larga duración. Los disparos se sienten fantásticos, es muy divertido luchar contra la IA y la variedad de poderes sobrenaturales que se ponen en tus manos solo ayudan a amplificar la carnicería. Deathloop es un juego obligatorio para todos los fanáticos de los juegos de disparos. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Titanfall 2", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/BtPSE5uKSwqcoLES6LHtAY-970-80.jpeg.webp", Description = "Titanfall 2 es un juego de disparos en primera persona subestimado de la última década. Es posible que Respawn Entertainment esté ocupado con Apex Legends ahora, pero si aún no lo ha jugado, se está perdiendo una de las mejores campañas en años. Es una historia sobre un piloto y su compañero robot mecánico, mientras exploran un mundo alienígena en constante disputa debido a las facciones enemigas. Corres por las paredes y te deslizas por el suelo, disparando a todo lo que ves con una serie de ingeniosas armas. Pero cada vez que te subes a tu robot, todo cambia, y ambas experiencias se vuelven una, ya que se entrelazan perfectamente entre sí. La historia ofrece niveles que siempre traen algo nuevo a la mesa, expandiendo las posibilidades de cada elemento del juego a niveles impensables." },
        new() { Category = GameCategoryOptions.Shots, Name = "Gears 5", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/Pq2YaFwVNSjNTJNJYJXphF-970-80.jpg.webp", Description = "No sería una lista de los mejores tiradores sin al menos un juego de Gears. Gears 5, aunque tal vez no sea la primera opción para los veteranos de la serie, aún captura lo que hizo que la franquicia fuera tan interesante a lo largo de los años. Una versión aún más refinada de disparar a cubierto, combinada con nuevas armas y un grupo completamente nuevo de enemigos para luchar mientras la protagonista Kait Diaz descubre el Swarm en una nueva y emocionante historia. Pero puedes saltar directamente incluso si no has jugado ninguna de las entradas anteriores, especialmente si estás interesado en jugar en modo cooperativo con tus amigos. La adición de Escape, un modo para tres jugadores en el que el trabajo en equipo es obligatorio mientras te infiltras en una colmena enemiga, colocas explosivos y tienes que huir de la escena de inmediato, es una adición bienvenida a un panorama multijugador ya variado. Y en Gears 5, ciertamente hay algo para todos.", IsFavourite = true },
        new() { Category = GameCategoryOptions.Shots, Name = "PUBG: Battlegrounds", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/XzFy5CXpR5edqJX3EDto4i-970-80.jpg.webp", Description = "El Battle Royale original es mejor que nunca. Si bien PlayerUnkown's Battlegrounds ha cedido algo de terreno a Apex Legends, Call of Duty: Warzones y Fortnites de este mundo, todavía tiene una ventaja táctica sobre su competencia más inmediata. Es más lento e implacable para los principiantes, con un mayor enfoque en la supervivencia, lo que solo ayuda a elevar los momentos de victoria incremental. Este juego de disparos en tercera persona recientemente se convirtió en un juego gratuito, imbuyendo a sus servidores con una nueva oportunidad de vida; hay una gran cantidad de contenido disponible en PUBG, desde una amplia gama de mapas hasta armas personalizables, y realmente deberías darle otra oportunidad si buscas un descanso de los otros Battle Royales principales. " },
        new() { Category = GameCategoryOptions.Shots, Name = "Half-Life Alyx", Likes = new Random().Next(50, 5000), Dislikes = new Random().Next(8, 500), Image = "https://cdn.mos.cms.futurecdn.net/sxSWinExz2y6HB76Rgijqh-970-80.jpg.webp", Description = "Muchos señalarán a Half-Life 2 como uno de los mejores juegos de disparos de todos los tiempos y, si bien sigue siendo una experiencia fantástica y formativa, hay verdadera magia en Half-Life Alyx. Esta exclusiva de realidad virtual muestra el poder y el potencial de la realidad virtual para los tiradores, brindándole un nivel de control y libertad sin precedentes para experimentar en un mundo al que estábamos tan desesperados por regresar. Al darnos un control complejo sobre las armas en nuestras manos y al diseñar escenarios verdaderamente reactivos, Valve pudo ofrecer uno de los mejores juegos de disparos de todos los tiempos. Confía en nosotros cuando te decimos que nunca has jugado nada tan inmersivo como Half-Life Alyx , un juego imprescindible si puedes conseguir la tecnología necesaria para ejecutarlo. " },
    };

    public async Task<List<GameCategory>> GetCategoriesWithGames()
    {
        await Task.Delay(1000);
        var gameCategories = new List<GameCategory>();
        gameCategories.Add(new() { Name = "Acción", Games = _games.Where(x => x.Category == GameCategoryOptions.Action).ToList() });
        gameCategories.Add(new() { Name = "Aventura", Games = _games.Where(x => x.Category == GameCategoryOptions.Adventure).ToList() });
        gameCategories.Add(new() { Name = "Belleza", Games = _games.Where(x => x.Category == GameCategoryOptions.Beauty).ToList() });
        gameCategories.Add(new() { Name = "Carrera", Games = _games.Where(x => x.Category == GameCategoryOptions.Races).ToList() });
        gameCategories.Add(new() { Name = "Clásicos", Games = _games.Where(x => x.Category == GameCategoryOptions.Classics).ToList() });
        gameCategories.Add(new() { Name = "Click", Games = _games.Where(x => x.Category == GameCategoryOptions.Click).ToList() });
        gameCategories.Add(new() { Name = "Deportes", Games = _games.Where(x => x.Category == GameCategoryOptions.Sports).ToList() });
        gameCategories.Add(new() { Name = "Puzzle", Games = _games.Where(x => x.Category == GameCategoryOptions.Puzzle).ToList() });
        gameCategories.Add(new() { Name = "Tiros", Games = _games.Where(x => x.Category == GameCategoryOptions.Shots).ToList() });
        return gameCategories;
    }

    public async Task<List<Game>> GetFavouriteGamesFromUser()
    {
        await Task.Delay(1000);
        return _games.Where(x => x.IsFavourite).ToList();
    }

    public async Task<Game?> GetGame(string name)
    {
        await Task.Delay(1000);
        foreach (var game in _games)
            if (game.Name.ToLower().Contains(name.ToLower()))
                return game;
        return null;
    }

    public async Task<Game?> GetOutstandingGame()
    {
        await Task.Delay(1000);
        foreach (var game in _games)
            if (game.IsOutstanding)
                return game;
        return null;
    }

    public async Task<List<Game>> SearchGames(string name, GameFilters? filters = null)
    {
        await Task.Delay(1000);
        var games = new List<Game>();
        foreach (var game in _games)
            if (game.Name.ToLower().Contains(name.ToLower()))
                games.Add(game);

        if (filters is null)
            return games;

        if (!string.IsNullOrWhiteSpace(filters.Category))
            games = games.Where(x => string.Compare(x.Category, filters.Category, CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace | CompareOptions.IgnoreCase) == 0).ToList();

        if (!string.IsNullOrWhiteSpace(filters.Popularity))
        {
            if (filters.Popularity == GamePopularityOptions.MorePopulars)
                games = games.OrderByDescending(x => x.Likes).ToList();
            else if (filters.Popularity == GamePopularityOptions.LessPopulars)
                games = games.OrderByDescending(x => x.Dislikes).ToList();
        }

        if (!string.IsNullOrWhiteSpace(filters.Order))
        {
            if (filters.Order == GameOrderOptions.Ascendant)
                games = games.OrderBy(x => x.Name).ToList();
            else if (filters.Order == GameOrderOptions.Descendant)
                games = games.OrderByDescending(x => x.Name).ToList();
        }
            
        return games;
    }
}
